### ISSUE TITLE
configure circleci

### ISSUE THREAD

**Issue by GitH3ll** [GitH3ll/tournamentTask#6]

**Comment by sashayakovtseva** [comment]
Config should contain jobs: `get source`, `build` and `test`.
Each job should be run after the previous one.
`Get source` job should save downloaded modules into the circleCI cache (see example [here](https://circleci.com/blog/continuous-integration-for-django-projects/) and [here](https://github.com/sylabs/scs-library-client/blob/master/.circleci/config.yml)).
